apiVersion: v1
kind: Service
metadata:
  name: {{ include "goliash.fullname" . }}
  labels: {{- include "goliash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "goliash.selector" . | nindent 4 }}
  ports:
    - { name: http, port: {{ .Values.service.port }}, targetPort: http }
